//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int AttachmentID { get; set; }
        public int BugID { get; set; }
        public string Name { get; set; }
        public string ContentPath { get; set; }
    
        public virtual Bugs Bugs { get; set; }
    }
}
