//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bugs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bugs()
        {
            this.Attachments = new HashSet<Attachments>();
        }
    
        public int BugID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssigneeID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public byte BugStatus { get; set; }
        public byte Priority { get; set; }
        public byte[] Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments> Attachments { get; set; }
        public virtual Users Users { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
