//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersToProjects
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Users Users { get; set; }
    }
}
